make baseDomain optional in parrot template

diff --git a/captainkube/azure-pipelines.deploy.yml b/captainkube/azure-pipelines.deploy.yml
--- a/captainkube/azure-pipelines.deploy.yml
+++ b/captainkube/azure-pipelines.deploy.yml
@@ -50,83 +50,88 @@ stages:
 
 
 
-  - stage:
-    displayName: Deploy to DEV
-    variables:
-      - name: kubernetesCluster
-        value: aks-boss-crawdad-dev
-    jobs:
-      - deployment: Dev
-        displayName: Deploy to Dev Environment
-        pool:
-          vmImage: 'ubuntu-latest'
-        environment: dev.apps
-        strategy:
-          runOnce:
-            deploy:
-              steps:
-                - checkout: none
+  # - stage:
+  #   displayName: Deploy to DEV
+  #   variables:
+  #     - name: kubernetesCluster
+  #       value: aks-boss-crawdad-dev
+  #   jobs:
+  #     - deployment: Dev
+  #       displayName: Deploy to Dev Environment
+  #       pool:
+  #         vmImage: 'ubuntu-latest'
+  #       environment: dev.apps
+  #       strategy:
+  #         runOnce:
+  #           deploy:
+  #             steps:
+  #               - checkout: none
 
-                - task: HelmInstaller@1
-                  displayName: 'Install Helm'
-                  inputs:
-                    helmVersionToInstall: 'latest'
+  #               - task: HelmInstaller@1
+  #                 displayName: 'Install Helm'
+  #                 inputs:
+  #                   helmVersionToInstall: 'latest'
 
-                - task: AzureCLI@2
-                  displayName: 'Prepare Deployment'
-                  env:
-                    AKS_RG: $(AZURE_ENV_RG)
-                    REGISTRY_SERVER: $(LOGIN_SERVER)
-                    CHART_PATH: $(local_chart_path)
-                  inputs:
-                    addSpnToEnvironment: true
-                    azureSubscription: 'Azure'
-                    failOnStandardError: true
-                    scriptLocation: 'inlineScript'
-                    scriptType: 'bash'
-                    inlineScript: |
-                      set -euo pipefail
+  #               - task: AzureCLI@2
+  #                 displayName: 'Prepare Deployment'
+  #                 env:
+  #                   AKS_RG: $(AZURE_ENV_RG)
+  #                   REGISTRY_SERVER: $(LOGIN_SERVER)
+  #                   CHART_PATH: $(local_chart_path)
+  #                 inputs:
+  #                   addSpnToEnvironment: true
+  #                   azureSubscription: 'Azure'
+  #                   failOnStandardError: true
+  #                   scriptLocation: 'inlineScript'
+  #                   scriptType: 'bash'
+  #                   inlineScript: |
+  #                     set -euo pipefail
 
-                      helm version
+  #                     helm version
 
-                      echo "Login to AKS"
-                      az aks get-credentials \
-                        --resource-group ${AKS_RG} \
-                        --name $(kubernetesCluster) \
-                        --admin \
-                        --overwrite-existing
+  #                     echo "Login to AKS"
+  #                     az aks get-credentials \
+  #                       --resource-group ${AKS_RG} \
+  #                       --name $(kubernetesCluster) \
+  #                       --admin \
+  #                       --overwrite-existing
 
-                      echo "Sanity Check"
-                      helm list -A
+  #                     echo "Sanity Check"
+  #                     helm list -A
 
-                      echo "Registry Login"
-                      echo $servicePrincipalKey | \
-                        helm registry login ${REGISTRY_SERVER} \
-                          --username $servicePrincipalId \
-                          --password-stdin
+  #                     echo "Registry Login"
+  #                     echo $servicePrincipalKey | \
+  #                       helm registry login ${REGISTRY_SERVER} \
+  #                         --username $servicePrincipalId \
+  #                         --password-stdin
 
-                      echo "Retrieve Artifact"
-                      helm chart pull $(artifact)
+  #                     echo "Retrieve Artifact"
+  #                     helm chart pull $(artifact)
 
-                      echo "Unpack Artifact"
-                      helm chart export "$(artifact)" --destination ./${CHART_PATH}
+  #                     echo "Unpack Artifact"
+  #                     helm chart export "$(artifact)" --destination ./${CHART_PATH}
 
-                      echo "Sanity Check"
-                      helm show chart ./${CHART_PATH}/$(containerRepository)
+  #                     echo "Sanity Check"
+  #                     helm show chart ./${CHART_PATH}/$(containerRepository)
 
-                - task: HelmDeploy@0
-                  inputs:
-                    connectionType: 'Azure Resource Manager'
-                    azureSubscription: 'Azure'
-                    azureResourceGroup: $(AZURE_ENV_RG)
-                    kubernetesCluster: $(kubernetesCluster)
-                    useClusterAdmin: true
-                    namespace: 'apps'
-                    command: 'upgrade'
-                    chartType: 'FilePath'
-                    chartPath: './$(local_chart_path)/$(containerRepository)'
-                    releaseName: '$(containerRepository)'
-                    overrideValues: 'image.tag=$(imageTag),image.repository=$(LOGIN_SERVER)/$(containerRepository)'
+  #               - task: HelmDeploy@0
+  #                 inputs:
+  #                   connectionType: 'Azure Resource Manager'
+  #                   azureSubscription: 'Azure'
+  #                   azureResourceGroup: $(AZURE_ENV_RG)
+  #                   kubernetesCluster: $(kubernetesCluster)
+  #                   useClusterAdmin: true
+  #                   namespace: 'apps'
+  #                   command: 'upgrade'
+  #                   chartType: 'FilePath'
+  #                   chartPath: './$(local_chart_path)/$(containerRepository)'
+  #                   releaseName: '$(containerRepository)'
+  #                   overrideValues: 'image.tag=$(imageTag),image.repository=$(LOGIN_SERVER)/$(containerRepository)'
+
+  - template: '../pipeline-templates/parrot-deployment.yml'
+    parameters:
+      environment: dev.apps
+      kubernetesCluster: aks-boss-crawdad-dev
 
   - template: '../pipeline-templates/parrot-deployment.yml'
     parameters:
